# Generated by Django 5.2.3 on 2025-07-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='catd_id',
            new_name='cart_id',
        ),
    ]
